services:
  app:
    build:
      context: .
    container_name: blog_app
    image: leandrofuccia/blog-app:${TIMESTAMP:-latest}
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      DOCKER_ENV: true
      DATABASE_USER: blogdb
      DATABASE_HOST: db
      DATABASE_NAME: blogdb
      DATABASE_PASSWORD: sua_senha_segura
      DATABASE_PORT: 5432
      JWT_SECRET: sua_chave_secreta
    depends_on:
      - db
    command: >
      bash ./wait-for-it.sh db:5432 -- sh -c "
      npm run typeorm migration:run &&
      node build/server.cjs"
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: blogdb
      POSTGRES_PASSWORD: sua_senha_segura
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
                 
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
