services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - DATABASE_USER=your_db_user
      - DATABASE_HOST=localhost
      - DATABASE_NAME=blogdb
      - DATABASE_PASSWORD=your_db_password
      - DATABASE_PORT=5432
      - JWT_SECRET=sua_chave_secreta
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: