services:
  app:
    build: .
    container_name: blog_app
    image: leandrofuccia/blog-app:latest
    ports:
      - "3002:3002"
    environment:
      - DATABASE_USER=blogdb
      - DATABASE_HOST=db
      - DATABASE_NAME=blogdb
      - DATABASE_PASSWORD=sua_senha_segura
      - DATABASE_PORT=5432
      - JWT_SECRET=sua_chave_secreta
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "build/server.cjs"]

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: blogdb
      POSTGRES_PASSWORD: sua_senha_segura
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb/01-create-and-populate.sql:/docker-entrypoint-initdb.d/01-create-and-populate.sql

volumes:
  db_data:
