CREATE TABLE Perfil (
    Id SERIAL PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL
);

CREATE TABLE Usuario (
    Id SERIAL PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Senha VARCHAR(50) NOT NULL,
    PerfilId INT NOT NULL,
    DataCriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UltimoLogin TIMESTAMP,
    FOREIGN KEY (PerfilId) REFERENCES Perfil(Id)
);

CREATE TABLE Postagem (
    Id SERIAL PRIMARY KEY,
    Titulo VARCHAR(150) NOT NULL,
    Conteudo TEXT NOT NULL,
    UsuarioId INT NOT NULL,
    DataCriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DataAtualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UsuarioId) REFERENCES Usuario(Id)
);